###############################
# geom_saberhilt
###############################

geom_saberhilt <- function(column = NULL) {
  list(
    geom_rect(aes(ymin = -10, 
                  ymax = 0, 
                  xmin = column - .05,
                  xmax = column + .05),
              fill = "gray60",
              colour = "black"),
    geom_rect(aes(ymin = -5, 
                  ymax = -20, 
                  xmin = column - .04,
                  xmax = column + .04),
              fill = "gray60",
              colour = "black"),
    geom_rect(aes(ymin = -4, 
                  ymax = -9, 
                  xmin = column - .055,
                  xmax = column + .055),
              fill = "gray60",
              colour = "black"),
    geom_rect(aes(ymin = -12, 
                  ymax = -20, 
                  xmin = column - .05,
                  xmax = column + .05),
              fill = "gray60",
              colour = "black"),
    geom_rect(aes(ymin = -1, 
                  ymax = 0, 
                  xmin = column - .06,
                  xmax = column + .06),
              fill = "gray60",
              colour = "black"),
    geom_rect(aes(ymin = -3, 
                  ymax = -4, 
                  xmin = column - .06,
                  xmax = column + .06),
              fill = "gray60",
              colour = "black"),
    geom_rect(aes(ymin = -12, 
                ymax = -13, 
                xmin = column - .06,
                xmax = column + .06),
            fill = "gray60",
              colour = "black"),
    geom_rect(aes(ymin = -14, 
                  ymax = -17, 
                  xmin = column - .000,
                  xmax = column + .055),
              fill = "gray60",
              colour = "black")
  )
}