---
title: "edld610_catd_finalproject"
author: "Cameron Kay"
date: "2/3/2019"
output:
  html_document:
    highlight: kate
    theme: cosmo
    toc: yes
    toc_depth: 3
    toc_float: yes
---

```{r initial_setup, include = FALSE}
# load necessary packages (if you do not have them, you will need to install them first)
library(tidyverse) # for dataframe manipulation and plotting
library(magrittr) # for updating an object that is piped into a function (using `%<>%`)
library(here) # for finding the project folder
library(repurrrsive) # contains the star wars datasets
library(rlist) # for binding all lit elements by column (using `list.cbind`)
library(ggrepel) # for adding geom_text labels that do not overlap
library(gganimate) # for animating the plot

# add gravitational constant (i.e., 6.67408 * 10^-11)
grav_constant <- 6.67408 * (10 ^ -11)

# load bespoke functions from the functions folder
source(here("functions/my_theme.R")) # load my_theme
source(here("functions/geom_saberhilt.R")) # load the function for creating the hilts of lightsabers
source(here("functions/geom_saberblade.R")) # load the function for creating the blades of lightsabers

# set figure output dimensions
knitr::opts_chunk$set(fig.width  = 12, 
                      fig.height = 8)

# set gganimate dimensions
#gganimatedev_args = list(width = 2000, height = 2000)
```

## The Data

### The People

```{r load_person_data, warning = FALSE}
# load and format data
people <- data.frame(t(list.cbind(sw_people))) %>%
  # convert the star wars people dataframe to a tibble
  as_tibble() %>%
  # select only the columns between name and gender (inclusive)
  select(name:gender) %>%
  # mutates columns that are lists to non-lists
  mutate_if(is.list, ~(unlist(.))) %>%
  # mutate all columns and replaces the text "unknown" with "NA"
  mutate_all(~(na_if(., "unknown"))) %>%
  # converts height and mass to numeric variables
  mutate_at(vars(height, mass), ~(as.numeric(.))) %>%
  # extracts birth year and converts it to numeric; replace "n/a" values with 
  # droid for hair_color and gender
  mutate(birth_year = parse_number(as.character(birth_year)),
         hair_color = if_else(gender == "n/a", "droid", hair_color),
         gender     = if_else(gender == "n/a", "droid", gender))

# look at first ten rows of tidied dataet
head(people, n = 10L)
```

### The Starships

```{r load_starships_data, warning = FALSE}
# load and format data
starships <- data.frame(t(list.cbind(sw_starships))) %>%
  # convert the star ways starship dataset to a tibble
  as_tibble() %>%
  # clean column names
  janitor::clean_names() %>%
  # select only those columns between name and starship (inclusive)
  select(name:starship_class) %>%
  # mutate columns that are lists to non-lists
  mutate_if(is.list, ~(unlist(.))) %>%
  # mutate all columns, replacing "unknown" with "NA"  
  mutate_all(~(na_if(., "unknown"))) %>%
  # convert numeric columns to numerics
  mutate_at(vars(cost_in_credits,
                 length,
                 crew,
                 passengers,
                 cargo_capacity,
                 hyperdrive_rating,
                 mglt), ~(as.numeric(.))) %>%
  # extract the max_atmosphering_speed and convert starship_class to a lowercase
  # factor
  mutate(max_atmosphering_speed = parse_number(max_atmosphering_speed),
         starship_class         = as.factor(tolower(starship_class))) %>%
  # seperate consumables into a value and unit (e.g., days, weeks, months, 
  # years)
  separate(consumables, c("con_n", "con_unit"), sep = " ") %>%
  # convert units to numeric values and multiply with the consumable value to 
  # provide the amount of consumable in the total number of days
  mutate(con_unit    = case_when(con_unit == "day"   ~ "1",
                                 con_unit == "week"  ~ "7",
                                 con_unit == "month" ~ "30",
                                 con_unit == "years" ~ "365"),
         consumables = as.numeric(con_n) * as.numeric(con_unit)) %>%
  # retain only the new consumables column (i.e., drop con_n and con_unit)
  select(-starts_with("con_"))

# look at first ten rows of tidied dataet
head(starships, n = 10L) 
```

### The Planets

```{r load_planets_data, warning = FALSE}
# load and format data
planets <- data.frame(t(list.cbind(sw_planets))) %>%
  # convert star wars planets dataset to a tibble
  as.tibble() %>%
  # retain only columns between name and population (inclusive)
  select(name:population) %>%
  # mutate columns that are lists to non-lists
  mutate_if(is.list, ~(unlist(.))) %>%
  # mutate all columns, replacing "unknown" with "NA"  
  mutate_all(~(na_if(., "unknown"))) %>%
  # convert numeric columns to type numeric
  mutate_at(vars(rotation_period,
                 orbital_period,
                 diameter,
                 surface_water,
                 population),
            ~(as.numeric(.))) %>%
  # calculate values of interest
  mutate(
         # make surface water a proportion
         surface_water   = surface_water / 100,
         # calculate population in millions
         population_mils = population / 1000000,
         # calculate a planet's distance from the sun (Kepler's 3rd law)
         au              = (((orbital_period / 365) ^ 2) ^ (1/3)),
         # convert gravity to a number
         gravity         = parse_number(as.character(gravity)),
         # calculate the force of gravity
         g               = gravity * 9.8, 
         # calculate radius
         radius          = diameter / 2, 
         # calculate planet mass (ish)
         mass            = (g * (radius^2)) / grav_constant,
         # calculate planet area
         area            = pi * (radius^2),
         # create column indicating whether the planet is in the solar system
         solar_system    = rep(FALSE, n()),
         # create a new variable indicating whether a planet was in the original 
         # trilogy
         orig_tril = case_when(name == "Alderaan" |
                               name == "Tatooine" |
                               name == "Yavin"    |
                               name == "Yavin 4"  ~ "new_hope",
                               name == "Bespin"   |
                               name == "Dagobah"  |                     
                               name == "Hoth"     ~ "empire_strikes",    
                               name == "Endor"    ~ "return_jedi",
                               TRUE ~ NA_character_))

# create dataset for planets in the solar system
sol_sys <- tibble(
  name           = c("Mercury", "Venus", "Earth", "Mars", "Jupiter"),
  orbital_period = c(       88,     225,     365,    687,      4330),
  au             = c(      .39,     .72,       1,   1.52,      5.20),
  solar_system   = c(     TRUE,    TRUE,    TRUE,   TRUE,      TRUE),
  radius         = c(   2439.5,    6052,    6378,   3396,     71492)
)

#combine the star war's planets and solar system data into one dataset
planets <- bind_rows(planets, sol_sys)

# look at first ten rows of tidied dataet
head(planets, n = 10L) 
```

## The Visualizations

### The People

```{r visualization_1}
# people plot
people %>%
  # filter for only females and males and drop the outlier (yoda)
  filter(gender == "female" | gender == "male",
         name   != "Yoda") %>%
  # group by gender
  group_by(gender) %>%
  # calculate mean age and rounded mean age for geom_text
  summarise(m_age   = mean(birth_year, na.rm = TRUE),
            m_age_r = round(m_age, 2),
            m_age_r = paste(m_age_r, "YEARS")) %>%
  # convert genders to title case and gender to a factor
  mutate(gender = str_to_title(gender),
         gender = as.factor(gender)) %>%
  # plot gender vs age and fill by gender
  ggplot(aes(x = gender, y = m_age, fill = gender)) +
    # add the lightsaber blades to the plot
    geom_saberblade() +
    # add the lightsaber hilts to the plot
    geom_saberhilt(column = 1) +
    geom_saberhilt(column = 2) +
    # set colour and fill values (i.e., red and green)
    scale_fill_manual(values   = c("#0FFF00", "#00f6ff")) +
    scale_colour_manual(values = c("#0FFF00", "#00f6ff")) +
    # add text with the mean ages to the plot
    geom_text(aes(label = m_age_r, color = gender), 
              size     = 6, 
              position = position_nudge(x = -.09, y = -8)) +
    # add labels
    labs(title     = "Average Age of Star Wars Characters by Gender",
           y       = "Age (years)",
           x       = "Gender",
           legend  = "Gender",
           caption = "Data from https://swapi.co.") +
    # customize using my theme
    my_theme() +
    # flip the coordinates
    coord_flip()

```

### The Starships
```{r visualization_2}
# generate random x, y, and transparency data to use for plotting stars
stars_data <- tibble(x     = sample(seq(from =  0, to =  4, by = .0001), 500),
                     y     = sample(seq(from =  0, to = 80, by = .0001), 500),
                     trans = sample(seq(from = .1, to = .9, by = .0001), 500))

# starships plot
starships %>%
  # group by starship_class
  group_by(starship_class) %>%
  # drop rows that have an NA for length 
  filter(!is.na(length)) %>%
  # calculate mean length and standard deviation, as well as number of ships in 
  # that class
  summarize(len_m  = mean(length),
            len_sd = sd(length),
            len_n  = n()) %>%
  # retain classes that have more than one ship
  filter(len_n > 1) %>%
  # convert starship_class to title case and wrap multi-word levels
  mutate(starship_class = str_to_title(starship_class),
         starship_class = gsub(" ", " \n", starship_class)) %>%
  # calculate standard error
  mutate(len_se = len_sd / sqrt(len_n)) %>%
  # plot starship class v starship length
  ggplot(aes(x = fct_reorder(starship_class, desc(len_m)), y = len_m)) +
    # add error bars
    geom_errorbar(aes(ymin = len_m - (len_se * qnorm(.975)), 
                      ymax = len_m + (len_se * qnorm(.975))), 
                  width = .5, colour = "grey70", lwd = 1.25) +
    geom_errorbar(aes(ymin = len_m - (len_se * qnorm(.975)), 
                      ymax = len_m + (len_se * qnorm(.975))), 
                  width = .5, colour = "grey30", lwd = 1) +
    # add stars 
    geom_point(data = stars_data, aes(x = x, y = y, alpha = trans), 
               colour = "white",
               size = .001) +
    # plot ship body points
    geom_point(size = 6.25, colour = "grey70") +
    geom_point(size = 6.00, colour = "grey30") +
    geom_point(size = 3.00, colour = "grey10") +
    geom_point(size = 4.00, colour = "grey60", shape = 13) +
    # add text for means
    geom_text(aes(label = starship_class),
              color = "deeppink2",
              face = "bold") +
    # flip the coordinates
    coord_flip() +
    # add labels
    labs(title   = "Average Length of Starship by Ship Class",
         y       = "Average Length in Meters",
         x       = "Class",
         caption = "Data from https://swapi.co.") + 
    # set y-axis limits and do not show value beyond limits of y-axis
    scale_y_continuous(limits = c(0,80), 
                       expand = expand_scale(mult = c(0, 0))) + 
    # customize using my theme
    my_theme() +
    theme(plot.margin  = unit(c(1, 1, 1, 1), "cm"),
          axis.title.y = element_text(vjust = 5))
```

### The Planets
```{r visualization_3, fig.height = 12, warning = FALSE}
# create function for calculating x axis locations during the time it takes
# bespin to make one rotation. There has to be enough slices to obscure the
# geom_points jumping back at the end of Bespin's year
orbit_slice <- function(planet = NULL) {
  # grab orbital period of planet of interest
  temp <- planets$orbital_period[which(planets$name == planet)]
  # calculate 511 x-axis point for that planet throughout Bespin' year
  rep(c(seq(from       = 0, 
            to         = 5110, 
            length.out = (510 * (temp / 5110))), 
        NA),
      length.out = 510)
}

# calculate locations on the x-axis for each planets during the time it takes
# bespin to make one rotation. 
orbital_degrees <- tibble(
  "Alderaan"   = orbit_slice("Alderaan"),
  "Hoth"       = orbit_slice("Hoth"),
  "Dagobah"    = orbit_slice("Dagobah"),
  "Bespin"     = orbit_slice("Bespin"),
  "Endor"      = orbit_slice("Endor"),
  "Tatooine"   = orbit_slice("Tatooine"),
  "Mercury"    = orbit_slice("Mercury"),
  "Venus"      = orbit_slice("Venus"),
  "Earth"      = orbit_slice("Earth"),
  "Mars"       = orbit_slice("Mars"),
  "Jupiter"    = orbit_slice("Jupiter"),
  "days_count" = 1:510
)

# gather days into a column and the planet names into another column
orbital_degrees %<>%
  gather(key = "name", value = "days", -days_count)

# planets plot
planets_plot <- planets %>%
  # select only variables of interest
  select(name, au, radius, orbital_period, orig_tril, solar_system) %>%
  # drop planets that do not have (1) a name, (2) a distance from the sun (i.e.
  # an AU), (3) an AU less than 2, and (4) a radius greater than 0.
  filter(!is.na(name),
         !is.na(au),
         !is.na(orbital_period),
         !is.na(orig_tril) | solar_system == TRUE,
         # au < 2,
         radius != 0.00) %>%
  left_join(orbital_degrees, by = "name") %>%
  #drop mercury and alderaan
  filter(name != "Mercury", # mercury for orbiting too quickly
         name != "Alderaan") %>% # alderaan for esssentially being earth 2.0
  # plot the planets distance from the sun against their arbitrary degree
  ggplot(aes(x = days, y = au, color = solar_system)) +
    # add labels indicating y-axis units and add star and earth
    geom_text(aes(x =   0,          y = 0, label = "STAR"), 
              color = "deeppink3", 
              size  = 5) +
    geom_text(aes(x = 5110 * 3 / 4, y = 2, label = "2 AU"), 
              color = "deeppink3", 
              size  = 5) +
    geom_text(aes(x = 5110 * 3 / 4, y = 4, label = "4 AU"), 
              color = "deeppink3", 
              size  = 5) +
    geom_text(aes(x = 5110 * 3 / 4, y = 6, label = "6 AU"), 
              color = "deeppink3", 
              size  = 5) +
    # add label for describing 1 AU
    annotate(geom  =                   "text", 
             x     =             5110 * 1 / 2,
             y     =                        7,
             label = "1 AU = ~150,000,000 km", 
             color =              "deeppink2",
             size  =                        5) +
    # add planet points; map size of the point to planet radius
    geom_point(aes(size = radius), alpha = .6) +
    # add planet text; also suppress its legend
    geom_text(aes(label   = name), 
              position    = position_nudge(y = 1.1), 
              alpha       = .7,
              size        =  5,
              show.legend = FALSE) +
    # make the coordinate polar
    coord_polar(theta = "x") +
    # add transition according to days
    transition_time(days_count) +
    # set the limit of size values
    scale_size_continuous(range = c(.5, 10)) +
    # drop x-axis grid marks and breaks
    scale_x_continuous(breaks = NULL) +
    # set 2-axis limit
    scale_y_continuous(limits = c(0, 7)) +
    # set the colours
    scale_colour_manual(name   = "Star System",
                        values = c("#02fff6", "#ffbc02"),
                        labels = c("Solar System", "Star Wars")) +
    # add labels
    labs(title    = "Distance from Host Star and Orbital Period",
         subtitle =                      "Days: {frame_time*10}", 
         caption  =                "Data from https://swapi.co.") +
    # customize using my theme
    my_theme() +
    # drop axis text and axis titles and center title, subtitle, and caption
    theme(plot.title      = element_text(hjust = 0.5),
          plot.subtitle   = element_text(hjust = 0.5),
          plot.caption    = element_text(hjust = 0.5),
          axis.text       = element_blank(),
          axis.title      = element_blank(),
          plot.margin     = unit(c(1, 5, 1, 7), "cm"),
          legend.position = "right") +
    # drop radius legend and change the size of the legend points
    guides(size = FALSE,
           colour = guide_legend(override.aes = list(size  = 5,
                                                     alpha = 1)))

# animate plot with a one-minute duration and 24 frames per second
animate(planets_plot, 
        duration = 1,
        fps      = 2)

``` 
